version: "3.8"
services:
  partner-service:
    container_name: partner-service
    image: amazoncorretto:19
    restart: unless-stopped
    volumes:
      - ./:/app
    command: bash -c "cd /app && java -jar partner-service-1.0.1-all.jar --port=8032"
    ports:
      - "8032:8032"
  candlestick-provider:
    container_name: candlesticks-web
    image: candlestick-provider:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/candlesticksdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgrespw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
      - partner-service
  postgres:
    image: "postgres:latest"
    container_name: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=candlesticksdb
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=mehmetccm@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin: